services:
  bucket:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"

  bucket-setup:
    # This container just create the bucket and set download permissions
    image: minio/mc
    depends_on:
      - bucket
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "sleep 5 && \
      mc alias set local http://bucket:9000 minioadmin minioadmin && \
      mc mb local/qr-app && \
      mc anonymous set download local/qr-app"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MINIO_ENDPOINT: bucket:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - bucket
