services:

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qr_app
    ports:
      - "5432:5432"
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  bucket:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"

  bucket-setup:
    # This container just create the bucket and set download permissions
    image: minio/mc
    depends_on:
      - bucket
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "sleep 5 && \
      mc alias set local http://bucket:9000 minioadmin minioadmin && \
      mc mb local/qr-app && \
      mc anonymous set download local/qr-app"

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - db
    # http://localhost:8080/?pgsql=postgres&server=db&username=user&db=qr_app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://user:password@db:5432/qr_app
      MINIO_ENDPOINT: bucket:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
      - bucket
