name: Check Python Style with Black

on:
  push:
    branches: [main]
    paths:
      - "**/*.py"
  pull_request:
    branches: [main]
    paths:
      - "**/*.py"

jobs:
  black-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Black
        run: pip install black

      - name: Run Black in check mode
        run: black --check --line-length 79 .
